<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Prime extends \FrxIntranet\FrxintranetBundle\Entity\Prime implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'primeNbcontratMin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'primeNbcontratMax', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'primeMontant', 'primePalier');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'primeNbcontratMin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'primeNbcontratMax', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Prime' . "\0" . 'primeMontant', 'primePalier');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Prime $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeNbcontratMin($primeNbcontratMin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeNbcontratMin', array($primeNbcontratMin));

        return parent::setPrimeNbcontratMin($primeNbcontratMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeNbcontratMin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeNbcontratMin', array());

        return parent::getPrimeNbcontratMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeNbcontratMax($primeNbcontratMax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeNbcontratMax', array($primeNbcontratMax));

        return parent::setPrimeNbcontratMax($primeNbcontratMax);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeNbcontratMax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeNbcontratMax', array());

        return parent::getPrimeNbcontratMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeMontant($primeMontant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeMontant', array($primeMontant));

        return parent::setPrimeMontant($primeMontant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeMontant', array());

        return parent::getPrimeMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimePalier(\FrxIntranet\FrxintranetBundle\Entity\Palier $primePalier = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimePalier', array($primePalier));

        return parent::setPrimePalier($primePalier);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimePalier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimePalier', array());

        return parent::getPrimePalier();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepot', array($depots));

        return parent::addDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepot', array($depots));

        return parent::removeDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepots()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepots', array());

        return parent::getDepots();
    }

}
