<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Pointeuse extends \FrxIntranet\FrxintranetBundle\Entity\Pointeuse implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointDate', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointHdebut', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointHfin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointNbh', 'pointUtil');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointDate', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointHdebut', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointHfin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Pointeuse' . "\0" . 'pointNbh', 'pointUtil');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Pointeuse $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointDate($pointDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointDate', array($pointDate));

        return parent::setPointDate($pointDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointDate', array());

        return parent::getPointDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointHdebut($pointHdebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointHdebut', array($pointHdebut));

        return parent::setPointHdebut($pointHdebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointHdebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointHdebut', array());

        return parent::getPointHdebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointHfin($pointHfin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointHfin', array($pointHfin));

        return parent::setPointHfin($pointHfin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointHfin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointHfin', array());

        return parent::getPointHfin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointNbh($pointNbh)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointNbh', array($pointNbh));

        return parent::setPointNbh($pointNbh);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointNbh()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointNbh', array());

        return parent::getPointNbh();
    }

    /**
     * {@inheritDoc}
     */
    public function setPointUtil(\FrxIntranet\FrxintranetBundle\Entity\Util $pointUtil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPointUtil', array($pointUtil));

        return parent::setPointUtil($pointUtil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointUtil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointUtil', array());

        return parent::getPointUtil();
    }

}
