<?php

namespace Proxies\__CG__\FrxIntranet\PrimeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Primeponct extends \FrxIntranet\PrimeBundle\Entity\Primeponct implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctMontant', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctDatedebut', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctDatefin', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctTitre', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctDescriptif', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctActive', 'primeponctDevise', 'primeponctUtil', 'primeponctPaye');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctMontant', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctDatedebut', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctDatefin', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctTitre', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctDescriptif', '' . "\0" . 'FrxIntranet\\PrimeBundle\\Entity\\Primeponct' . "\0" . 'primeponctActive', 'primeponctDevise', 'primeponctUtil', 'primeponctPaye');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Primeponct $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctMontant($primeponctMontant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctMontant', array($primeponctMontant));

        return parent::setPrimeponctMontant($primeponctMontant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctMontant', array());

        return parent::getPrimeponctMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctDatedebut($primeponctDatedebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctDatedebut', array($primeponctDatedebut));

        return parent::setPrimeponctDatedebut($primeponctDatedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctDatedebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctDatedebut', array());

        return parent::getPrimeponctDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctDatefin($primeponctDatefin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctDatefin', array($primeponctDatefin));

        return parent::setPrimeponctDatefin($primeponctDatefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctDatefin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctDatefin', array());

        return parent::getPrimeponctDatefin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctActive($primeponctActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctActive', array($primeponctActive));

        return parent::setPrimeponctActive($primeponctActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctActive', array());

        return parent::getPrimeponctActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctDevise(\FrxIntranet\ComptabiliteBundle\Entity\Devise $primeponctDevise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctDevise', array($primeponctDevise));

        return parent::setPrimeponctDevise($primeponctDevise);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctDevise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctDevise', array());

        return parent::getPrimeponctDevise();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctUtil(\FrxIntranet\FrxintranetBundle\Entity\Util $primeponctUtil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctUtil', array($primeponctUtil));

        return parent::setPrimeponctUtil($primeponctUtil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctUtil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctUtil', array());

        return parent::getPrimeponctUtil();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctTitre($primeponctTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctTitre', array($primeponctTitre));

        return parent::setPrimeponctTitre($primeponctTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctTitre', array());

        return parent::getPrimeponctTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctDescriptif($primeponctDescriptif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctDescriptif', array($primeponctDescriptif));

        return parent::setPrimeponctDescriptif($primeponctDescriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctDescriptif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctDescriptif', array());

        return parent::getPrimeponctDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrimeponctPaye(\FrxIntranet\FrxintranetBundle\Entity\Paye $primeponctPaye = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrimeponctPaye', array($primeponctPaye));

        return parent::setPrimeponctPaye($primeponctPaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponctPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponctPaye', array());

        return parent::getPrimeponctPaye();
    }

}
