<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Palier extends \FrxIntranet\FrxintranetBundle\Entity\Palier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Palier' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Palier' . "\0" . 'palierBorne1', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Palier' . "\0" . 'palierBorne2', 'primes');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Palier' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Palier' . "\0" . 'palierBorne1', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Palier' . "\0" . 'palierBorne2', 'primes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Palier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPalierBorne1($palierBorne1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPalierBorne1', array($palierBorne1));

        return parent::setPalierBorne1($palierBorne1);
    }

    /**
     * {@inheritDoc}
     */
    public function getPalierBorne1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPalierBorne1', array());

        return parent::getPalierBorne1();
    }

    /**
     * {@inheritDoc}
     */
    public function setPalierBorne2($palierBorne2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPalierBorne2', array($palierBorne2));

        return parent::setPalierBorne2($palierBorne2);
    }

    /**
     * {@inheritDoc}
     */
    public function getPalierBorne2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPalierBorne2', array());

        return parent::getPalierBorne2();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrime(\FrxIntranet\FrxintranetBundle\Entity\Prime $primes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrime', array($primes));

        return parent::addPrime($primes);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrime(\FrxIntranet\FrxintranetBundle\Entity\Prime $primes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrime', array($primes));

        return parent::removePrime($primes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimes', array());

        return parent::getPrimes();
    }

}
