<?php

namespace Proxies\__CG__\FrxIntranet\ComptabiliteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Exercice extends \FrxIntranet\ComptabiliteBundle\Entity\Exercice implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceDatedebut', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceDatefin', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceCredit', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceDebit', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceResultat', 'exerciceDevise', 'frais');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceDatedebut', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceDatefin', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceCredit', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceDebit', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Exercice' . "\0" . 'exerciceResultat', 'exerciceDevise', 'frais');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Exercice $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setExerciceDatedebut($exerciceDatedebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExerciceDatedebut', array($exerciceDatedebut));

        return parent::setExerciceDatedebut($exerciceDatedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciceDatedebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciceDatedebut', array());

        return parent::getExerciceDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setExerciceDatefin($exerciceDatefin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExerciceDatefin', array($exerciceDatefin));

        return parent::setExerciceDatefin($exerciceDatefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciceDatefin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciceDatefin', array());

        return parent::getExerciceDatefin();
    }

    /**
     * {@inheritDoc}
     */
    public function setExerciceCredit($exerciceCredit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExerciceCredit', array($exerciceCredit));

        return parent::setExerciceCredit($exerciceCredit);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciceCredit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciceCredit', array());

        return parent::getExerciceCredit();
    }

    /**
     * {@inheritDoc}
     */
    public function setExerciceDebit($exerciceDebit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExerciceDebit', array($exerciceDebit));

        return parent::setExerciceDebit($exerciceDebit);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciceDebit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciceDebit', array());

        return parent::getExerciceDebit();
    }

    /**
     * {@inheritDoc}
     */
    public function setExerciceResultat($exerciceResultat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExerciceResultat', array($exerciceResultat));

        return parent::setExerciceResultat($exerciceResultat);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciceResultat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciceResultat', array());

        return parent::getExerciceResultat();
    }

    /**
     * {@inheritDoc}
     */
    public function setExerciceDevise(\FrxIntranet\ComptabiliteBundle\Entity\Devise $exerciceDevise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExerciceDevise', array($exerciceDevise));

        return parent::setExerciceDevise($exerciceDevise);
    }

    /**
     * {@inheritDoc}
     */
    public function getExerciceDevise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExerciceDevise', array());

        return parent::getExerciceDevise();
    }

    /**
     * {@inheritDoc}
     */
    public function addFrai(\FrxIntranet\ComptabiliteBundle\Entity\Frais $frais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFrai', array($frais));

        return parent::addFrai($frais);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFrai(\FrxIntranet\ComptabiliteBundle\Entity\Frais $frais)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFrai', array($frais));

        return parent::removeFrai($frais);
    }

    /**
     * {@inheritDoc}
     */
    public function getFrais()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFrais', array());

        return parent::getFrais();
    }

}
