<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Paye extends \FrxIntranet\FrxintranetBundle\Entity\Paye implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeDatedebut', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeDatefin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeNbDepot', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeNbRetrait', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeMontantDepot', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeMontantRetrait', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeSommeDeduite', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payePourcentage', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payePrime', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeNbHoraire', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeTauxHoraire', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeTauxEuro', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeMontant', 'depots', 'retraits', 'primes', 'payeUtil');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeDatedebut', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeDatefin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeNbDepot', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeNbRetrait', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeMontantDepot', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeMontantRetrait', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeSommeDeduite', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payePourcentage', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payePrime', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeNbHoraire', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeTauxHoraire', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeTauxEuro', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Paye' . "\0" . 'payeMontant', 'depots', 'retraits', 'primes', 'payeUtil');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Paye $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeDatedebut($payeDatedebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeDatedebut', array($payeDatedebut));

        return parent::setPayeDatedebut($payeDatedebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeDatedebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeDatedebut', array());

        return parent::getPayeDatedebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeDatefin($payeDatefin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeDatefin', array($payeDatefin));

        return parent::setPayeDatefin($payeDatefin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeDatefin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeDatefin', array());

        return parent::getPayeDatefin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeNbDepot($payeNbDepot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeNbDepot', array($payeNbDepot));

        return parent::setPayeNbDepot($payeNbDepot);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeNbDepot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeNbDepot', array());

        return parent::getPayeNbDepot();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeNbRetrait($payeNbRetrait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeNbRetrait', array($payeNbRetrait));

        return parent::setPayeNbRetrait($payeNbRetrait);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeNbRetrait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeNbRetrait', array());

        return parent::getPayeNbRetrait();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeMontantDepot($payeMontantDepot)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeMontantDepot', array($payeMontantDepot));

        return parent::setPayeMontantDepot($payeMontantDepot);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeMontantDepot()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeMontantDepot', array());

        return parent::getPayeMontantDepot();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeMontantRetrait($payeMontantRetrait)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeMontantRetrait', array($payeMontantRetrait));

        return parent::setPayeMontantRetrait($payeMontantRetrait);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeMontantRetrait()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeMontantRetrait', array());

        return parent::getPayeMontantRetrait();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeSommeDeduite($payeSommeDeduite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeSommeDeduite', array($payeSommeDeduite));

        return parent::setPayeSommeDeduite($payeSommeDeduite);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeSommeDeduite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeSommeDeduite', array());

        return parent::getPayeSommeDeduite();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayePourcentage($payePourcentage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayePourcentage', array($payePourcentage));

        return parent::setPayePourcentage($payePourcentage);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayePourcentage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayePourcentage', array());

        return parent::getPayePourcentage();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayePrime($payePrime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayePrime', array($payePrime));

        return parent::setPayePrime($payePrime);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayePrime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayePrime', array());

        return parent::getPayePrime();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeNbHoraire($payeNbHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeNbHoraire', array($payeNbHoraire));

        return parent::setPayeNbHoraire($payeNbHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeNbHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeNbHoraire', array());

        return parent::getPayeNbHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeTauxHoraire($payeTauxHoraire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeTauxHoraire', array($payeTauxHoraire));

        return parent::setPayeTauxHoraire($payeTauxHoraire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeTauxHoraire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeTauxHoraire', array());

        return parent::getPayeTauxHoraire();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeTauxEuro($payeTauxEuro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeTauxEuro', array($payeTauxEuro));

        return parent::setPayeTauxEuro($payeTauxEuro);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeTauxEuro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeTauxEuro', array());

        return parent::getPayeTauxEuro();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeMontant($payeMontant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeMontant', array($payeMontant));

        return parent::setPayeMontant($payeMontant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeMontant', array());

        return parent::getPayeMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepot', array($depots));

        return parent::addDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepot', array($depots));

        return parent::removeDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepots()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepots', array());

        return parent::getDepots();
    }

    /**
     * {@inheritDoc}
     */
    public function addRetrait(\FrxIntranet\FrxintranetBundle\Entity\Retrait $retraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRetrait', array($retraits));

        return parent::addRetrait($retraits);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRetrait(\FrxIntranet\FrxintranetBundle\Entity\Retrait $retraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRetrait', array($retraits));

        return parent::removeRetrait($retraits);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetraits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetraits', array());

        return parent::getRetraits();
    }

    /**
     * {@inheritDoc}
     */
    public function setPayeUtil(\FrxIntranet\FrxintranetBundle\Entity\Util $payeUtil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPayeUtil', array($payeUtil));

        return parent::setPayeUtil($payeUtil);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayeUtil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayeUtil', array());

        return parent::getPayeUtil();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrime(\FrxIntranet\PrimeBundle\Entity\Primeponct $primes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrime', array($primes));

        return parent::addPrime($primes);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrime(\FrxIntranet\PrimeBundle\Entity\Primeponct $primes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrime', array($primes));

        return parent::removePrime($primes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimes', array());

        return parent::getPrimes();
    }

}
