<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Depot extends \FrxIntranet\FrxintranetBundle\Entity\Depot implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotDate', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotNumMonth', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotMontant', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotPrime', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotFirstdeposit', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotPoucent', 'depotClient', 'depotPaye', 'depotUtil');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotDate', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotNumMonth', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotMontant', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotPrime', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotFirstdeposit', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Depot' . "\0" . 'depotPoucent', 'depotClient', 'depotPaye', 'depotUtil');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Depot $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotDate($depotDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotDate', array($depotDate));

        return parent::setDepotDate($depotDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotDate', array());

        return parent::getDepotDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotNumMonth($depotNumMonth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotNumMonth', array($depotNumMonth));

        return parent::setDepotNumMonth($depotNumMonth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotNumMonth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotNumMonth', array());

        return parent::getDepotNumMonth();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotMontant($depotMontant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotMontant', array($depotMontant));

        return parent::setDepotMontant($depotMontant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotMontant', array());

        return parent::getDepotMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotFirstdeposit($depotFirstdeposit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotFirstdeposit', array($depotFirstdeposit));

        return parent::setDepotFirstdeposit($depotFirstdeposit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotFirstdeposit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotFirstdeposit', array());

        return parent::getDepotFirstdeposit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotPourcent($depotPourcent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotPourcent', array($depotPourcent));

        return parent::setDepotPourcent($depotPourcent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotPourcent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotPourcent', array());

        return parent::getDepotPourcent();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotClient(\FrxIntranet\FrxintranetBundle\Entity\Client $depotClient = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotClient', array($depotClient));

        return parent::setDepotClient($depotClient);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotClient', array());

        return parent::getDepotClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotPaye(\FrxIntranet\FrxintranetBundle\Entity\Paye $depotPaye = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotPaye', array($depotPaye));

        return parent::setDepotPaye($depotPaye);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotPaye()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotPaye', array());

        return parent::getDepotPaye();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotUtil(\FrxIntranet\FrxintranetBundle\Entity\Util $depotUtil = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotUtil', array($depotUtil));

        return parent::setDepotUtil($depotUtil);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotUtil()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotUtil', array());

        return parent::getDepotUtil();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotPrime($depotPrime)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotPrime', array($depotPrime));

        return parent::setDepotPrime($depotPrime);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotPrime()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotPrime', array());

        return parent::getDepotPrime();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepotPoucent($depotPoucent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepotPoucent', array($depotPoucent));

        return parent::setDepotPoucent($depotPoucent);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepotPoucent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepotPoucent', array());

        return parent::getDepotPoucent();
    }

}
