<?php

namespace Proxies\__CG__\FrxIntranet\ComptabiliteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Frais extends \FrxIntranet\ComptabiliteBundle\Entity\Frais implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisDate', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisTitre', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisDescriptif', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisMontant', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisFixe', 'fraisDevise', 'fraisExercice');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisDate', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisTitre', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisDescriptif', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisMontant', '' . "\0" . 'FrxIntranet\\ComptabiliteBundle\\Entity\\Frais' . "\0" . 'fraisFixe', 'fraisDevise', 'fraisExercice');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Frais $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisDate($fraisDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisDate', array($fraisDate));

        return parent::setFraisDate($fraisDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisDate', array());

        return parent::getFraisDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisTitre($fraisTitre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisTitre', array($fraisTitre));

        return parent::setFraisTitre($fraisTitre);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisTitre', array());

        return parent::getFraisTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisDescriptif($fraisDescriptif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisDescriptif', array($fraisDescriptif));

        return parent::setFraisDescriptif($fraisDescriptif);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisDescriptif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisDescriptif', array());

        return parent::getFraisDescriptif();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisMontant($fraisMontant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisMontant', array($fraisMontant));

        return parent::setFraisMontant($fraisMontant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisMontant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisMontant', array());

        return parent::getFraisMontant();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisFixe($fraisFixe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisFixe', array($fraisFixe));

        return parent::setFraisFixe($fraisFixe);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisFixe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisFixe', array());

        return parent::getFraisFixe();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisDevise(\FrxIntranet\ComptabiliteBundle\Entity\Devise $fraisDevise = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisDevise', array($fraisDevise));

        return parent::setFraisDevise($fraisDevise);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisDevise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisDevise', array());

        return parent::getFraisDevise();
    }

    /**
     * {@inheritDoc}
     */
    public function setFraisExercice(\FrxIntranet\ComptabiliteBundle\Entity\Exercice $fraisExercice = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFraisExercice', array($fraisExercice));

        return parent::setFraisExercice($fraisExercice);
    }

    /**
     * {@inheritDoc}
     */
    public function getFraisExercice()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFraisExercice', array());

        return parent::getFraisExercice();
    }

}
