<?php

namespace FrxIntranet\PrimeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PrimeponctRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrimeponctRepository extends EntityRepository
{
     //Recup toutes les primes pour un User entre 2 dates
    public function recupPrime($datedebut, $datefin, $util) {
      $datedebut = new \DateTime($datedebut);
      $datefin   = new \DateTime($datefin);
      $primes = $this->createQueryBuilder('a')
                ->where('(a.primeponctActive = true) AND (a.primeponctUtil = :util) AND (a.primeponctDatefin BETWEEN :datedebut AND :datefin )ORDER BY a.primeponctDevise')
                ->setParameter('datedebut', $datedebut)
                ->setParameter('datefin', $datefin)
                ->setParameter('util', $util)
                ->getQuery()
                ->getResult();
        
        return $primes;
    }
    
    
}
