<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Client extends \FrxIntranet\FrxintranetBundle\Entity\Client implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientNum', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientNom', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientTel', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientMail', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientSolde', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientAdresse', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientVille', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientComment', 'depots', 'retraits');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientNum', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientNom', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientTel', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientMail', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientSolde', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientAdresse', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientVille', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Client' . "\0" . 'clientComment', 'depots', 'retraits');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Client $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNum($clientNum)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNum', array($clientNum));

        return parent::setClientNum($clientNum);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNum()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNum', array());

        return parent::getClientNum();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientNom($clientNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientNom', array($clientNom));

        return parent::setClientNom($clientNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientNom', array());

        return parent::getClientNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientTel($clientTel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientTel', array($clientTel));

        return parent::setClientTel($clientTel);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientTel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientTel', array());

        return parent::getClientTel();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientMail($clientMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientMail', array($clientMail));

        return parent::setClientMail($clientMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientMail', array());

        return parent::getClientMail();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientSolde($clientSolde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientSolde', array($clientSolde));

        return parent::setClientSolde($clientSolde);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientSolde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientSolde', array());

        return parent::getClientSolde();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientAdresse($clientAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientAdresse', array($clientAdresse));

        return parent::setClientAdresse($clientAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientAdresse', array());

        return parent::getClientAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientComment($clientComment)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientComment', array($clientComment));

        return parent::setClientComment($clientComment);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientComment()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientComment', array());

        return parent::getClientComment();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepot', array($depots));

        return parent::addDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepot', array($depots));

        return parent::removeDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepots()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepots', array());

        return parent::getDepots();
    }

    /**
     * {@inheritDoc}
     */
    public function setClientVille($clientVille)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClientVille', array($clientVille));

        return parent::setClientVille($clientVille);
    }

    /**
     * {@inheritDoc}
     */
    public function getClientVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClientVille', array());

        return parent::getClientVille();
    }

    /**
     * {@inheritDoc}
     */
    public function addRetrait(\FrxIntranet\FrxintranetBundle\Entity\Retrait $retraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRetrait', array($retraits));

        return parent::addRetrait($retraits);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRetrait(\FrxIntranet\FrxintranetBundle\Entity\Retrait $retraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRetrait', array($retraits));

        return parent::removeRetrait($retraits);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetraits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetraits', array());

        return parent::getRetraits();
    }

}
