<?php

namespace Proxies\__CG__\FrxIntranet\FrxintranetBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Util extends \FrxIntranet\FrxintranetBundle\Entity\Util implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilLogin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilNom', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilPrenom', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilAdresse', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilMail', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilTel1', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilTel2', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilPassword', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilActive', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilAdmin', 'depots', 'retraits', 'pointages', 'payes', 'primeponcts');
        }

        return array('__isInitialized__', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'id', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilLogin', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilNom', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilPrenom', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilAdresse', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilMail', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilTel1', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilTel2', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilPassword', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilActive', '' . "\0" . 'FrxIntranet\\FrxintranetBundle\\Entity\\Util' . "\0" . 'utilAdmin', 'depots', 'retraits', 'pointages', 'payes', 'primeponcts');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Util $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilLogin($utilLogin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilLogin', array($utilLogin));

        return parent::setUtilLogin($utilLogin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilLogin', array());

        return parent::getUtilLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilNom($utilNom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilNom', array($utilNom));

        return parent::setUtilNom($utilNom);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilNom', array());

        return parent::getUtilNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilPrenom($utilPrenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilPrenom', array($utilPrenom));

        return parent::setUtilPrenom($utilPrenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilPrenom', array());

        return parent::getUtilPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilAdresse($utilAdresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilAdresse', array($utilAdresse));

        return parent::setUtilAdresse($utilAdresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilAdresse', array());

        return parent::getUtilAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilTel1($utilTel1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilTel1', array($utilTel1));

        return parent::setUtilTel1($utilTel1);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilTel1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilTel1', array());

        return parent::getUtilTel1();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilTel2($utilTel2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilTel2', array($utilTel2));

        return parent::setUtilTel2($utilTel2);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilTel2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilTel2', array());

        return parent::getUtilTel2();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilPassword($utilPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilPassword', array($utilPassword));

        return parent::setUtilPassword($utilPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilPassword', array());

        return parent::getUtilPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilActive($utilActive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilActive', array($utilActive));

        return parent::setUtilActive($utilActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilActive', array());

        return parent::getUtilActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilAdmin($utilAdmin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilAdmin', array($utilAdmin));

        return parent::setUtilAdmin($utilAdmin);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilAdmin', array());

        return parent::getUtilAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function addDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDepot', array($depots));

        return parent::addDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDepot(\FrxIntranet\FrxintranetBundle\Entity\Depot $depots)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDepot', array($depots));

        return parent::removeDepot($depots);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepots()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepots', array());

        return parent::getDepots();
    }

    /**
     * {@inheritDoc}
     */
    public function addRetrait(\FrxIntranet\FrxintranetBundle\Entity\Retrait $retraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRetrait', array($retraits));

        return parent::addRetrait($retraits);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRetrait(\FrxIntranet\FrxintranetBundle\Entity\Retrait $retraits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRetrait', array($retraits));

        return parent::removeRetrait($retraits);
    }

    /**
     * {@inheritDoc}
     */
    public function getRetraits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRetraits', array());

        return parent::getRetraits();
    }

    /**
     * {@inheritDoc}
     */
    public function addPointage(\FrxIntranet\FrxintranetBundle\Entity\Pointeuse $pointages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPointage', array($pointages));

        return parent::addPointage($pointages);
    }

    /**
     * {@inheritDoc}
     */
    public function removePointage(\FrxIntranet\FrxintranetBundle\Entity\Pointeuse $pointages)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePointage', array($pointages));

        return parent::removePointage($pointages);
    }

    /**
     * {@inheritDoc}
     */
    public function getPointages()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPointages', array());

        return parent::getPointages();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilMail($utilMail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilMail', array($utilMail));

        return parent::setUtilMail($utilMail);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilMail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilMail', array());

        return parent::getUtilMail();
    }

    /**
     * {@inheritDoc}
     */
    public function addPaye(\FrxIntranet\FrxintranetBundle\Entity\Paye $payes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPaye', array($payes));

        return parent::addPaye($payes);
    }

    /**
     * {@inheritDoc}
     */
    public function removePaye(\FrxIntranet\FrxintranetBundle\Entity\Paye $payes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePaye', array($payes));

        return parent::removePaye($payes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPayes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPayes', array());

        return parent::getPayes();
    }

    /**
     * {@inheritDoc}
     */
    public function addPrimeponct(\FrxIntranet\PrimeBundle\Entity\Primeponct $primeponcts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPrimeponct', array($primeponcts));

        return parent::addPrimeponct($primeponcts);
    }

    /**
     * {@inheritDoc}
     */
    public function removePrimeponct(\FrxIntranet\PrimeBundle\Entity\Primeponct $primeponcts)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePrimeponct', array($primeponcts));

        return parent::removePrimeponct($primeponcts);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrimeponcts()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrimeponcts', array());

        return parent::getPrimeponcts();
    }

}
