parameters:
#    prime.example.class: FrxIntranet\PrimeBundle\Example

services:
#    prime.example:
#        class: %prime.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
