<?php

namespace FrxIntranet\FrxintranetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DepotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends EntityRepository
{
    
    //Recup toutes les depots pour un User entre 2 dates
    public function recupDepot($datedebut, $datefin, $util) {
      $datedebut = new \DateTime($datedebut);
      $datefin   = new \DateTime($datefin);
      $depots = $this->createQueryBuilder('a')
                ->where('(a.depotUtil = :util) AND (a.depotDate BETWEEN :datedebut AND :datefin )')
                ->setParameter('datedebut', $datedebut)
                ->setParameter('datefin', $datefin)
                ->setParameter('util', $util)
                ->getQuery()
                ->getResult();
        
        return $depots;
    }
    
}
