<?php

namespace FrxIntranet\FrxintranetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PayeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PayeRepository extends EntityRepository
{
}
