<?php

namespace FrxIntranet\FrxintranetBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PointeuseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointeuseRepository extends EntityRepository {

    //Recup toutes les horaires pour un User entre 2 dates
    public function recupHoraire($datedebut, $datefin, $util) {
        $datedebut = new \DateTime($datedebut);
        $datefin = new \DateTime($datefin);
        $horaires = $this->createQueryBuilder('a')
                ->where('(a.pointUtil = :util) AND (a.pointDate BETWEEN :datedebut AND :datefin )')
                ->setParameter('datedebut', $datedebut)
                ->setParameter('datefin', $datefin)
                ->setParameter('util', $util)
                ->getQuery()
                ->getResult();

        return $horaires;
    }

    public function additionHoraire($horaires) {
        
        $heure = 0;
       
         
       
        //die ($addition);
        foreach ($horaires as $horaire) {
            $heure += $horaire->getPointNbh()->format('H') *3600 + $horaire->getPointNbh()->format('i') *60 + $horaire->getPointNbh()->format('s');  ;
            //$heure = $heure * 3600;
            
        }
        $hour = floor($heure /3600);
        $min = floor($heure%3600/60);
        $sec = $heure - (($hour*3600) + ($min*60));
        $result = $hour.":".$min.":".$sec;

        return $result;
    }

}
