<?php

namespace FrxIntranet\ComptabiliteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RecurrenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecurrenceRepository extends EntityRepository
{
}
